# Generated by Django 5.2.17 on 2026-09-25 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit_hours', models.PositiveSmallIntegerField(default=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='convoka_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
