# Generated by Django 5.2.17 on 2026-09-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='daily_limit_hours',
            field=models.DecimalField(decimal_places=1, default=6, max_digits=4),
        ),
    ]
