# Generated by Django 5.2.17 on 2026-09-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usersettings_daily_limit_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='provider',
            field=models.CharField(blank=True, max_length=200, verbose_name='proveedor o encargado'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='target_time',
            field=models.TimeField(blank=True, null=True, verbose_name='hora objetivo'),
        ),
    ]
