# Generated by Django 5.2.17 on 2026-09-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usersettings_daily_limit_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='provider',
            field=models.CharField(blank=True, max_length=200, verbose_name='proveedor'),
        ),
    ]
