# Generated by Django 5.2.17 on 2026-10-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_subtask_provider_subtask_target_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='allow_overload',
            field=models.BooleanField(default=False, help_text='Permite programar gestiones en un día aunque se supere el límite diario.', verbose_name='permitir sobrecarga diaria'),
        ),
    ]
