# Generated by Django 5.2.17 on 2026-10-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_usersettings_allow_overload"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="allow_overdue_subtasks",
            field=models.BooleanField(
                default=False,
                help_text="Permite crear o reprogramar gestiones con fecha anterior a hoy.",
                verbose_name="permitir gestiones vencidas",
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="allow_subtasks_after_event",
            field=models.BooleanField(
                default=False,
                help_text="Permite que una gestión tenga fecha posterior a la fecha de su evento.",
                verbose_name="permitir gestiones después del evento",
            ),
        ),
    ]
